name: spbu-computational-workshop
version: 0.1.0.0
github: "WoWaster/spbu-computational-workshop"
license: BSD3
author: "Nikolai Ponomarev"
maintainer: "wowasterdev@gmail.com"
copyright: "2023 Nikolai Ponomarev"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/WoWaster/spbu-computational-workshop#readme>

dependencies:
  - base >= 4.7 && < 5
  - pretty-simple
  - numbers
  - table-layout

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fspecialise-aggressively

language: GHC2021

library:
  source-dirs: src

_exe-ghc-options: &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  interpolation:
    main: Main.hs
    source-dirs: app/interpolation
    ghc-options: *exe-ghc-options
    dependencies:
      - spbu-computational-workshop
  backwardInterpolation:
    main: Main.hs
    source-dirs: app/backwardInterpolation
    ghc-options: *exe-ghc-options
    dependencies:
      - spbu-computational-workshop
  numericalDifferentiation:
    main: Main.hs
    source-dirs: app/numericalDifferentiation
    ghc-options: *exe-ghc-options
    dependencies:
      - spbu-computational-workshop
  basicIntegration:
    main: Main.hs
    source-dirs: app/basicIntegration
    ghc-options: *exe-ghc-options
    dependencies:
      - spbu-computational-workshop
  compoundIntegration:
    main: Main.hs
    source-dirs: app/compoundIntegration
    ghc-options: *exe-ghc-options
    dependencies:
      - spbu-computational-workshop
  rungeMethod:
    main: Main.hs
    source-dirs: app/rungeMethod
    ghc-options: *exe-ghc-options
    dependencies:
      - spbu-computational-workshop

tests:
  spbu-computational-workshop-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - spbu-computational-workshop
